CREATE TABLE`produto`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `descricao` varchar(150) DEFAULT NULL,
    `link_foto` varchar(200) DEFAULT NULL,
    `tipo_produto` int(11) NOT NULL,
    `tipo_percurso` int(11) DEFAULT NULL,
    `lixo` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY(`id`),
    KEY`fk_produto_lista1_idx`(`tipo_produto`),
    KEY`fk_produto_lista2_idx`(`tipo_percurso`),
    CONSTRAINT`fk_produto_lista1` FOREIGN KEY(`tipo_produto`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_produto_lista2` FOREIGN KEY(`tipo_percurso`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 62 DEFAULT CHARSET = utf8



CREATE TABLE`produto_lote_inscricao`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `lote_inscricao_id` int(11) NOT NULL,
    `produto_id` int(11) DEFAULT NULL,
    `descricao` varchar(100) DEFAULT NULL,
    `valor` double NOT NULL,
    `idade_minima` int(11) DEFAULT NULL,
    `idade_maxima` int(11) DEFAULT NULL,
    `lixo` tinyint(1) NOT NULL DEFAULT '0',
    `publicar_lista` tinyint(1) NOT NULL DEFAULT '0',
    `limite_por_pessoa` int(11) DEFAULT NULL,
    `limite` int(11) DEFAULT NULL,
    `adicional_nao_filiado` tinyint(1) NOT NULL DEFAULT '0',
    `adicional_anuidade_pendente` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY(`id`),
    KEY`fk_produto_has_lote_inscricao_lote_inscricao1_idx`(`lote_inscricao_id`),
    KEY`fk_produto_lote_inscricao_produto1_idx`(`produto_id`),
    CONSTRAINT`fk_produto_has_lote_inscricao_lote_inscricao1` FOREIGN KEY(`lote_inscricao_id`) REFERENCES`lote_inscricao`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_produto_lote_inscricao_produto1` FOREIGN KEY(`produto_id`) REFERENCES`produto`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 8957 DEFAULT CHARSET = utf8

CREATE TABLE`evento`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `descricao` varchar(200) NOT NULL,
    `categoria_modelo_id` int(11) DEFAULT NULL,
    `inicio` datetime NOT NULL,
    `fim` datetime NOT NULL,
    `abrangencia` int(11) NOT NULL,
    `etapa` varchar(30) NOT NULL,
    `sigla` varchar(25) NOT NULL,
    `organizador` varchar(150) NOT NULL,
    `pais` varchar(100) NOT NULL,
    `estado` int(11) NOT NULL,
    `cidade` varchar(100) NOT NULL,
    `endereco` varchar(150) NOT NULL,
    `latitude` varchar(20) DEFAULT NULL,
    `longitude` varchar(20) DEFAULT NULL,
    `contato` varchar(150) NOT NULL,
    `site` varchar(200) DEFAULT NULL,
    `lixo` tinyint(1) NOT NULL DEFAULT '0',
    `entidade_id` int(11) DEFAULT NULL,
    `esporte_id` int(11) DEFAULT NULL,
    `campeonato_id` int(11) DEFAULT NULL,
    `informacao_inscricao` text,
    `evento_aceite_id` int(11) DEFAULT NULL,
    `evento_site` tinyint(1) NOT NULL DEFAULT '0',
    `configuracao_site` text,
    `privado` tinyint(1) NOT NULL DEFAULT '0',
    `evento_espelhado_id` int(11) DEFAULT NULL,
    `entidade_pai_id` int(11) DEFAULT NULL,
    `email_atleta` tinyint(1) NOT NULL DEFAULT '0',
    PRIMARY KEY(`id`),
    KEY`fk_evento_entidade1_idx`(`entidade_id`),
    KEY`fk_evento_esporte1_idx`(`esporte_id`),
    KEY`fk_evento_lista_1_idx`(`abrangencia`),
    KEY`fk_evento_lista2_idx`(`estado`),
    KEY`fk_evento_campeonato1_idx`(`campeonato_id`),
    KEY`fk_evento_categoria_modelo1_idx`(`categoria_modelo_id`),
    KEY`fk_evento_evento_aceite1_idx`(`evento_aceite_id`),
    KEY`fk_evento_evento1_idx`(`evento_espelhado_id`),
    KEY`fk_evento_entidade2_idx`(`entidade_pai_id`),
    CONSTRAINT`fk_evento_campeonato1` FOREIGN KEY(`campeonato_id`) REFERENCES`campeonato`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_categoria_modelo1` FOREIGN KEY(`categoria_modelo_id`) REFERENCES`categoria_modelo`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_entidade1` FOREIGN KEY(`entidade_id`) REFERENCES`entidade`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_entidade2` FOREIGN KEY(`entidade_pai_id`) REFERENCES`entidade`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_esporte1` FOREIGN KEY(`esporte_id`) REFERENCES`esporte`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_evento1` FOREIGN KEY(`evento_espelhado_id`) REFERENCES`evento`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_evento_aceite1` FOREIGN KEY(`evento_aceite_id`) REFERENCES`evento_aceite`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_lista1` FOREIGN KEY(`abrangencia`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_evento_lista2` FOREIGN KEY(`estado`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 1281 DEFAULT CHARSET = utf8


CREATE TABLE`inscricao`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `lancamento` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `evento_id` int(11) NOT NULL,
    `lote_inscricao_id` int(11) NOT NULL,
    `lixo` tinyint(1) NOT NULL DEFAULT '0',
    `status` int(11) NOT NULL,
    `valor_bruto` double NOT NULL DEFAULT '0',
    `valor_pago` double NOT NULL DEFAULT '0',
    `pessoa_fisica_id` int(11) NOT NULL,
    `tipo_pagamento` int(11) NOT NULL,
    `observacao` text,
    `comprovante` varchar(254) DEFAULT NULL,
    `transacao_eletronica_id` int(11) DEFAULT NULL,
    PRIMARY KEY(`id`),
    KEY`fk_inscricao_evento1_idx`(`evento_id`),
    KEY`fk_inscricao_lote_inscricao1_idx`(`lote_inscricao_id`),
    KEY`fk_inscricao_lista1_idx`(`status`),
    KEY`fk_inscricao_pessoa_fisica1_idx`(`pessoa_fisica_id`),
    KEY`fk_inscricao_lista2_idx`(`tipo_pagamento`),
    KEY`fk_inscricao_transacao_eletronica1_idx`(`transacao_eletronica_id`),
    CONSTRAINT`fk_inscricao_evento1` FOREIGN KEY(`evento_id`) REFERENCES`evento`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_lista1` FOREIGN KEY(`status`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_lista2` FOREIGN KEY(`tipo_pagamento`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_lote_inscricao1` FOREIGN KEY(`lote_inscricao_id`) REFERENCES`lote_inscricao`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica1` FOREIGN KEY(`pessoa_fisica_id`) REFERENCES`pessoa_fisica`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_transacao_eletronica1` FOREIGN KEY(`transacao_eletronica_id`) REFERENCES`transacao_eletronica`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 48940 DEFAULT CHARSET = utf8


CREATE TABLE`inscricao_pessoa_fisica`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `inscricao_id` int(11) NOT NULL,
    `pessoa_fisica_id` int(11) NOT NULL,
    `lixo` tinyint(1) NOT NULL,
    `status` int(11) NOT NULL,
    `observacao` text,
    `valor_total` double NOT NULL DEFAULT '0',
    `sicard` varchar(20) DEFAULT NULL,
    `categoria_id` int(11) DEFAULT NULL,
    `clube_id` int(11) DEFAULT NULL,
    `federacao_id` int(11) DEFAULT NULL,
    `tamanho_camiseta` varchar(2) DEFAULT NULL,
    `email` varchar(150) DEFAULT NULL,
    PRIMARY KEY(`id`),
    KEY`fk_inscricao_pessoa_inscricao1_idx`(`inscricao_id`),
    KEY`fk_inscricao_pessoa_pessoa_fisica1_idx`(`pessoa_fisica_id`),
    KEY`fk_inscricao_pessoa_fisica_lista1_idx`(`status`),
    KEY`fk_inscricao_pessoa_fisica_categoria1_idx`(`categoria_id`),
    KEY`fk_inscricao_pessoa_fisica_entidade1_idx`(`clube_id`),
    KEY`fk_inscricao_pessoa_fisica_entidade2_idx`(`federacao_id`),
    CONSTRAINT`fk_inscricao_pessoa_fisica_categoria1` FOREIGN KEY(`categoria_id`) REFERENCES`categoria`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica_entidade1` FOREIGN KEY(`clube_id`) REFERENCES`entidade`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica_entidade2` FOREIGN KEY(`federacao_id`) REFERENCES`entidade`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica_lista1` FOREIGN KEY(`status`) REFERENCES`lista`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_inscricao1` FOREIGN KEY(`inscricao_id`) REFERENCES`inscricao`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_pessoa_fisica1` FOREIGN KEY(`pessoa_fisica_id`) REFERENCES`pessoa_fisica`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 68771 DEFAULT CHARSET = utf8

CREATE TABLE`lista`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `descricao` varchar(100) NOT NULL,
    `sigla` varchar(5) NOT NULL,
    `indice` int(11) NOT NULL,
    `complemento` varchar(20) DEFAULT NULL,
    `lixo` tinyint(1) NOT NULL,
    `lista_grupo_id` int(11) NOT NULL,
    PRIMARY KEY(`id`),
    KEY`fk_lista_lista_grupo1_idx`(`lista_grupo_id`),
    CONSTRAINT`fk_lista_lista_grupo1` FOREIGN KEY(`lista_grupo_id`) REFERENCES`lista_grupo`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 174 DEFAULT CHARSET = utf8

CREATE TABLE`inscricao_pessoa_fisica_produto_lote`(
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `inscricao_pessoa_fisica_id` int(11) NOT NULL,
    `produto_lote_inscricao_id` int(11) NOT NULL,
    `inscricao_id` int(11) NOT NULL,
    `lixo` tinyint(1) NOT NULL,
    `quantidade` tinyint(4) NOT NULL DEFAULT '1',
    `valor` double DEFAULT NULL,
    `valor_adicional` double DEFAULT NULL,
    PRIMARY KEY(`id`),
    KEY`fk_inscricao_pessoa_fisica_produto_lote_inscricao_pessoa_fi_idx`(`inscricao_pessoa_fisica_id`),
    KEY`fk_inscricao_pessoa_fisica_produto_lote_produto_lote_inscri_idx`(`produto_lote_inscricao_id`),
    KEY`fk_inscricao_pessoa_fisica_produto_lote_inscricao1_idx`(`inscricao_id`),
    CONSTRAINT`fk_inscricao_pessoa_fisica_produto_lote_inscricao1` FOREIGN KEY(`inscricao_id`) REFERENCES`inscricao`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica_produto_lote_inscricao_pessoa_fisi1` FOREIGN KEY(`inscricao_pessoa_fisica_id`) REFERENCES`inscricao_pessoa_fisica`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT`fk_inscricao_pessoa_fisica_produto_lote_produto_lote_inscricao1` FOREIGN KEY(`produto_lote_inscricao_id`) REFERENCES`produto_lote_inscricao`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB AUTO_INCREMENT = 119330 DEFAULT CHARSET = utf8

